DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS holdings;


CREATE TABLE users (
	uid TEXT PRIMARY KEY,
	email TEXT NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE holdings (
	id TEXT PRIMARY KEY,
	uid TEXT NOT NULL,
	ticker TEXT NOT NULL,
	count INTEGER NOT NULL,
	buy_price REAL NOT NULL,
	created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
